### ISSUE TITLE
rake aborted redmine 5.0.2 ruby 3.1.2

### ISSUE THREAD

**Issue by ashrafalzyoud** [ozguryazilimas/redmine_default_assignee#12]
```
redmine@redmine:~/5.0.2$ bundle exec rake redmine:plugins:migrate RAILS_ENV=production
rake aborted!
LoadError: cannot load such file -- redmine_default_assignee
/home/redmine/5.0.2/plugins/redmine_default_assignee/init.rb:2:in `<top (required)>'
/home/redmine/5.0.2/lib/redmine/plugin_loader.rb:31:in `load'
/home/redmine/5.0.2/lib/redmine/plugin_loader.rb:31:in `run_initializer'
/home/redmine/5.0.2/lib/redmine/plugin_loader.rb:108:in `each'
/home/redmine/5.0.2/lib/redmine/plugin_loader.rb:108:in `block in load'
/home/redmine/5.0.2/config/environment.rb:16:in `<top (required)>'
/home/redmine/.rbenv/versions/3.1.2/bin/bundle:25:in `load'
/home/redmine/.rbenv/versions/3.1.2/bin/bundle:25:in `<main>'
Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)

```

**Comment by zaburt** [comment]
Plugin is now Redmine 5.0.3 compatible.
