### ISSUE TITLE
Cant access settings of project with latest version

### ISSUE THREAD

**Issue by Nethe** [ozguryazilimas/redmine_default_assignee#4]
Hi, 

i just installed the plugin to my redmine, enabled the Default assigne in project settings, but getting this error:

```
root@motv_redmine:/opt/redmine/log# tailf production.log 
  plugins/redmine_default_assignee/app/models/rda_project_setting.rb:14:in `block in <class:RdaProjectSetting>'
  plugins/redmine_default_assignee/app/views/projects/_rda_project_settings.erb:1:in `_d97419fe1d0cca5a23e2a83d585529b0'
  app/views/common/_tabs.html.erb:17:in `block in _1028013defdec1c0c22ec57e884dfe38'
  app/views/common/_tabs.html.erb:16:in `each'
  app/views/common/_tabs.html.erb:16:in `_1028013defdec1c0c22ec57e884dfe38'
  app/helpers/application_helper.rb:325:in `render_tabs'
  app/views/projects/settings.html.erb:3:in `_3d15cd8175a32ae45c9051299aa412ee'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```
The environment is:
```
Environment:
  Redmine version                3.3.4.stable
  Ruby version                   2.3.3-p222 (2016-11-21) [x86_64-linux-gnu]
  Rails version                  4.2.7.1
  Environment                    production
  Database adapter               PostgreSQL
SCM:
  Git                            2.11.0
  Filesystem                     
Redmine plugins:
  additionals                    2.0.11
  periodictask                   3.3.1
  redmine_default_assignee       0.6.0
```
I am not able to reach the project settings now. Is there some way of how to fix it? 
Thank you!

**Comment by zaburt** [comment]
I would expect this to work fine actually. Could you verify you have run the plugin migrations ? They should have created rda_project_settings table in your redmine database. If you have not run them, or in doubt you can run with this command. Even if you have run it before you can rerun it.

    RAILS_ENV=production bundle exec rake redmine:plugins:migrate

**Comment by Nethe** [comment]
Hi, sorry, my mistake. I forgot to do this. Thank you!
